name = "Fields"
uuid = "54c0c897-3bff-4ba2-acae-d4c1acf2c14a"
authors = ["Thomas Burton <tburton5572@gmail.com>"]
version = "0.24.3"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
IniFile = "83e8ac13-25f8-5344-8a64-a9f2b223428f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
ResolventAnalysis = "8e664b2d-fea9-4945-a6a3-91764c96093d"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ChebUtils = "5c307136-fb89-411d-b568-fbf16049e5ad"
FDGrids = "28eb41cd-435a-4ede-8bdb-f2685fc03e8c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "ChebUtils", "FDGrids", "BenchmarkTools"]
